language: java

services:
  - mysql
  - postgresql
  - redis-server

addons:
  postgresql: "9.5"

before_script:
  - export MYSQL_TEST=ENABLED
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - export PG_TEST=ENABLED
  - psql -c 'CREATE DATABASE "test";' -U postgres
  - export REDIS_TEST=ENABLED
  - chmod +x gradlew

after_success:
  - cat /home/travis/build/hackorama/mcore/build/reports/spotbugs/main.html
  - bash <(curl -s https://codecov.io/bash)

