language: java

services:
  - mysql
  - postgresql
  - redis-server

addons:
  postgresql: "10"

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'CREATE DATABASE "test";' -U postgres
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)

