language: java

services:
  - mysql
  - redis-server

addons:
  postgresql: "10"

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'CREATE DATABASE test;' -U postgres

sudo: false

before_script:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)

