language: java

services:
  - mysql
  - postgresql
  - redis-server

addons:
  postgresql: "9.5"

before_script:
  - export MYSQL_TEST=ENABLED
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - export PG_TEST=ENABLED
  - psql -c 'CREATE DATABASE "test";' -U postgres
  - export REDIS_TEST=ENABLED
  - chmod +x gradlew

# Removing assemble step https://github.com/travis-ci/travis-ci/issues/8667
# Required for sub projects depending on local maven published artifact from root project
install: true

script: travis_wait ./gradlew --console=plain check

after_success:
  - bash <(curl -s https://codecov.io/bash)


